version: '3.9'
services:
  web:
    image: node:20
    working_dir: /app
    volumes:
      - ./apps/web:/app
    command: pnpm dev
    ports:
      - '3000:3000'
  rembg:
    build: ./services/rembg
    ports:
      - '7000:7000'
